title: My Blog
author: Favour CHibueze
email: fazzy140@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Testing how to deploy using github pages with jekyll

# social links
twitter_username: favourchi__ # DO NOT include the @ character, or else the build will fail!
github_username:  favour-chibueze # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
